repos:

  - repo: https://github.com/ambv/black
    rev: 19.3b0
    hooks:
    - id: black
      language_version: python3.10

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    - id: isort
      args: ["--profile", "black"]

  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    - id: flake8


  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910-1
    hooks:
    - id: mypy
      verbose: true
      args: [--python-version=3.10, --install-types, --non-interactive]