CREATE USER 'APPLICATION_USER'@'%' IDENTIFIED BY 'application-user-password';

GRANT ALL PRIVILEGES ON *.* TO 'APPLICATION_USER'@'%' WITH GRANT OPTION;

GRANT SELECT ON DOCK.* TO 'APPLICATION_USER'@'%';
GRANT INSERT ON DOCK.* TO 'APPLICATION_USER'@'%';
GRANT UPDATE ON DOCK.* TO 'APPLICATION_USER'@'%';
GRANT DELETE ON DOCK.* TO 'APPLICATION_USER'@'%';

FLUSH PRIVILEGES;